spring:
  kafka:
    bootstrap-servers: 192.168.234.120:9092
    consumer:
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: my-group
    listener:
      ack-mode: manual
